version: '3'
services:
  guro:
    # tomar la imagen del dockerfile
    build: .
    container_name: guro
    working_dir: /app
    restart: unless-stopped
    volumes:
      - .:/app
    command: >
      sh -c "yarn build &&
             yarn start"
    ports:
      - 3001:3000
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    expose:
      - 3001