# Generated by Django 4.2 on 2023-04-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('telefono_cliente', models.CharField(max_length=50)),
                ('email_cliente', models.EmailField(max_length=254)),
                ('nombre_beneficiario', models.CharField(max_length=50)),
                ('nombre_banco', models.CharField(max_length=50)),
                ('cuenta_beneficiario', models.CharField(max_length=50)),
                ('importe', models.FloatField()),
                ('tasa', models.FloatField()),
                ('total', models.FloatField()),
                ('estado', models.IntegerField(choices=[(0, 'Pendiente'), (1, 'En proceso'), (2, 'Completado'), (3, 'Cancelado')], default=0)),
            ],
        ),
    ]
