# Generated by Django 4.2 on 2023-04-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferencia', '0002_cliente_remove_transferencia_cuenta_beneficiario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuenta',
            old_name='tipo_cuenta',
            new_name='cedula',
        ),
        migrations.AddField(
            model_name='cuenta',
            name='nombre_cuenta',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
